import subprocess
from pathlib import Path

from home_os.extensions import db
from home_os.models.share import Share


class ShareService:
    def __init__(self, storage_root):
        from home_os.config import ROOT_DIR

        self.storage_root = Path(storage_root)
        if not self.storage_root.is_absolute():
            self.storage_root = ROOT_DIR / self.storage_root

    def list_shares(self):
        return Share.query.order_by(Share.created_at.desc()).all()

    def _validate_share_name(self, name):
        import re
        if not name or len(name) > 80:
            raise ValueError("Share name must be 1-80 characters")
        if not re.match(r'^[a-zA-Z0-9_\- ]+$', name):
            raise ValueError("Share name can only contain letters, numbers, spaces, hyphens, underscores")
        return name.strip()

    def create_share(self, name, path, read_only=False, guest_access=False):
        name = self._validate_share_name(name)

        resolved = (self.storage_root / path.lstrip("/")).resolve()
        try:
            resolved.relative_to(self.storage_root.resolve())
        except ValueError:
            raise PermissionError("Path must be within storage root")

        if not resolved.is_dir():
            raise FileNotFoundError(f"Directory not found: {path}")

        if Share.query.filter_by(name=name).first():
            raise ValueError(f"Share name '{name}' already exists")

        share = Share(
            name=name,
            path=str(resolved),
            read_only=read_only,
            guest_access=guest_access,
        )
        db.session.add(share)
        db.session.commit()
        self._write_smb_config()
        return share

    def delete_share(self, share_id):
        share = Share.query.get(share_id)
        if not share:
            raise FileNotFoundError("Share not found")
        db.session.delete(share)
        db.session.commit()
        self._write_smb_config()

    def toggle_share(self, share_id):
        share = Share.query.get(share_id)
        if not share:
            raise FileNotFoundError("Share not found")
        share.is_active = not share.is_active
        db.session.commit()
        self._write_smb_config()
        return share

    def _write_smb_config(self):
        """Generate smb.conf sections for active shares."""
        shares = Share.query.filter_by(is_active=True).all()

        lines = [
            "# Auto-generated by Home OS — do not edit manually",
            "",
        ]

        for share in shares:
            lines.extend([
                f"[{share.name}]",
                f"   path = {share.path}",
                f"   browseable = yes",
                f"   read only = {'yes' if share.read_only else 'no'}",
                f"   guest ok = {'yes' if share.guest_access else 'no'}",
                f"   create mask = 0664",
                f"   directory mask = 0775",
                "",
            ])

        conf_path = self.storage_root.parent / "config" / "smb_shares.conf"
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text("\n".join(lines))

        self._reload_samba()

    def _reload_samba(self):
        """Reload Samba config. Fails silently if Samba isn't installed."""
        try:
            subprocess.run(
                ["sudo", "smbcontrol", "all", "reload-config"],
                capture_output=True,
                timeout=5,
            )
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass
