[Service]
Environment=HOME_OS_MUSIC_CACHE_DIR=/run/home-os/music-streams
Environment=HOME_OS_MUSIC_FEED_CACHE_DIR=/run/home-os/music-feeds
Environment=HOME_OS_MUSIC_GENRE_CACHE_DIR=/var/cache/home-os/music-genres
Environment=HOME_OS_MUSIC_METADATA_CACHE_DIR=/var/cache/home-os/music-metadata
Environment=HOME_OS_YTDLP_CACHE_DIR=/var/cache/home-os/yt-dlp
Environment=HOME_OS_MUSIC_AUDIO_CACHE_DIR=/var/cache/home-os/music-audio
RuntimeDirectory=home-os
RuntimeDirectoryMode=0700
CacheDirectory=home-os
CacheDirectoryMode=0700
